language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CKiX2ZoZFcko2weNqcwBhc3CPJIBXARt+YUK261xbyAJZ238eHhfzNwCkcGT7GGYHZxYob77EjRfIrRYGC56V33ru+tYV13Pnx/4JDpgWxYkxpnPtjxzwm9cBOCTj03XGHeql2iDDD+4izSAwc1iGfl6JdZGY/Ie63zbgSLCZJAQeI6IRyzPrlbNlERQyTXjGv70EOg0Mg7rEZb/HRSb07wIcx7SI77eBZXO6WOtcKvIjTMkoOpOgk93yFcIeHtDRv1TKCsNqbdcdhb1NkkeX84dU+6AIMk+mwvbTh9tJMVJx7pfXTFvzl3l9KvnfSdQ32Vtsx95Pe3Mv/i8Wi0vMZmpADRdP99vzx9hXjLa3o+IcrZ/sjcY8GgwOow1MBiZT+TF4XyFS4bACEi1ah6M3hkbHZVvH2cDoUb9AuwYdEYnluhG8AlXm/Fhre8+D3/5J4CtczMxKj0RS6wJVeRu0DnPPIqN6zz2quWyJEs7nodvc3jEctUUk6K68sescI6PAUHlfaCS5HtlLtjaG1CTyNTEKakhYyClYRcSz6SiivO0I5yLteTZp03ldZ2lWhleUER2fFnVE4JO4XceTjzgE2j32Z0UTz8ELCAjKy3n9FjdPNSrNeOwf2xn2c7Q8TJ7UsTAqzyDhI+WGYq7XL1xudjkNXHQbyrVp16qN9guO+4=
  app: gentle-beyond-15457
  skip_cleanup: true
  on:
    repo: JordanMichele/nodeCapstone
